version: '3.8'

services:
  bot:
    build:
      context: .  
      dockerfile: docker/Dockerfile
    container_name: rocket_launch_bot
    env_file:
      - .env
    volumes:
      - .:/opt/rocket_bot
    command: python bot/rocket_launch_bot.py
