version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rocket_launch_bot
    env_file:
      - dev.env
    volumes:
      - .:/app
    command: poetry run python rocket_launch_bot.py
    restart: always

