version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: rocket_launch_bot
    env_file:
      - dev.env
    volumes:
      - .:/bot
    command: poetry run python bot/rocket_launch_bot.py

